// frontend-react/src/components/browser/browser.tsx
import { Link, useHistory } from "react-router-dom";
import { Api } from "../../api";
import { BibItem } from "../../entities";
import { useQuery } from "../../util";
import { useState, useEffect } from "react";
import React from "react";

const Browser = () => {
  const history = useHistory();
  const query = useQuery();
  const uri = query.get('uri');
  const isRoot = !uri;
  const mopidyServerName = query.get('name')!;

  const [items, setItems] = useState<BibItem[]>([]);
  const [state, setLoadingState] = useState<"loading" | "done" | "failed">("loading");

  useEffect(() => {
    setLoadingState("loading");
    Api.browse(uri, mopidyServerName)
      .then(items => {
        setItems(items);
        setLoadingState("done");
      })
      .catch(err => {
        console.log(err);
        setItems([]);
        setLoadingState("failed");
      });
  }, [uri, mopidyServerName]);

  function stop() {
    Api.stop(mopidyServerName);
    history.push("/");
  }

  function playUris(uris: string[]) {
    Api.play(uris, mopidyServerName);
    history.push("/");
  }

  const trackUris = items
    .filter(item => item.type === 'track')
    .map(item => item.uri);

  return (
    <div className="col">
      <div className="list-group">
        {isRoot && <button className="list-group-item list-group-item-action" onClick={() => stop()}>
          Playback stoppen
        </button>}
        {trackUris.length > 0 && <button className="list-group-item list-group-item-action active" onClick={() => playUris(trackUris)}>
          Alle abspielen
        </button>}
        {state === "loading" && <div className="list-group-item">Lade...</div>}
        {state === "failed" && <div className="list-group-item list-group-item-danger">
            Daten konnten nicht geladen werden.
          </div>}
        {state === "done" && items.map(item => <React.Fragment key={item.uri}>
          {item.type === 'track' ? <button onClick={() => playUris([item['uri']])} className="list-group-item list-group-item-action">
            {item.name}
          </button> :
            <Link to={`/browse?uri=${encodeURIComponent(item.uri)}&name=${encodeURIComponent(mopidyServerName)}`} className="list-group-item list-group-item-action">
              {item.name}
            </Link>}
        </React.Fragment>)}
      </div>
    </div>
  );
}

export default Browser;

// frontend/src/app/browser/browser.component.ts
import { Component, OnInit } from '@angular/core';
import {ActivatedRoute, ParamMap, Router} from '@angular/router';
import {BibItem} from '../bib-item';
import {ApiService} from '../api.service';

@Component({
  selector: 'app-browser',
  templateUrl: './browser.component.html',
  styleUrls: ['./browser.component.css']
})
export class BrowserComponent implements OnInit {
  items: BibItem[] = [];
  mopidyServerName: string;
  isRoot: boolean = false;

  constructor(
    private activatedRoute: ActivatedRoute,
    private api: ApiService,
    private router: Router
  ) { }

  ngOnInit() {
    this.activatedRoute.queryParamMap.subscribe((params: ParamMap) => {
      const uri = params.get('uri');
      this.isRoot = !uri;
      this.mopidyServerName = params.get('name');
      this.api.browse(uri, this.mopidyServerName).subscribe((items: BibItem[]) => {
        this.items = items;
      });
    });
  }

  public stop() {
    this.api.stop(this.mopidyServerName);
  }

  public playUris(uris: string[]) {
    this.api.play(uris, this.mopidyServerName);
    this.router.navigateByUrl('/');
  }

  public getTrackUris(): string[] {
    return this.items
      .filter((item: BibItem) => item.type === 'track')
      .map((item: BibItem) => item.uri);
  }
}

<div class="col">
  <div class="list-group">
    <a *ngIf="isRoot"
       class="list-group-item list-group-item-action"
       href="javascript:void(0)"
       (click)="stop()">
      Playback stoppen
    </a>
    <a *ngIf="getTrackUris().length > 0"
       class="list-group-item list-group-item-action active"
       href="javascript:void(0)"
       (click)="playUris(getTrackUris())">
      Alle abspielen
    </a>
    <ng-container *ngFor="let item of items">
      <a *ngIf="item.type === 'track'"
         href="javascript:void(0)" (click)="playUris([item['uri']])"
         class="list-group-item list-group-item-action">
        {{ item['name'] }}
      </a>
      <a *ngIf="item.type !== 'track'"
         [routerLink]="['/browse']" [queryParams]="{uri: item['uri'], name: mopidyServerName}"
         class="list-group-item list-group-item-action">
        {{ item['name'] }}
      </a>
    </ng-container>
  </div>
</div>
