// frontend/src/app/streams/streams.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {ApiService} from '../api.service';
import {Stream} from '../stream';
import {Client} from '../client';
import {MopidyServer} from '../mopidy-server';
import {ActivatedRoute, ParamMap} from '@angular/router';
import 'rxjs/add/operator/filter';
import {TimerObservable} from 'rxjs/observable/TimerObservable';
import 'rxjs/add/operator/takeWhile';
import 'rxjs/add/operator/first';

@Component({
  selector: 'app-streams',
  templateUrl: './streams.component.html',
  styleUrls: ['./streams.component.css']
})
export class StreamsComponent implements OnInit, OnDestroy {
  streams: Stream[] = [];
  clients: Client[] = [];
  mopidyServers: MopidyServer[] = [];
  isAdmin: boolean;

  private refreshInterval = 2000;
  private alive: boolean;

  constructor(
    public api: ApiService,
    private activatedRoute: ActivatedRoute
  ) { }

  ngOnInit(): void {
    this.activatedRoute.queryParamMap.subscribe((params: ParamMap) => {
      this.isAdmin = ['true', '1'].indexOf(params.get('is_admin')) > -1;
    });
    this.alive = true;

    TimerObservable.create(0, this.refreshInterval)
      .takeWhile(() => this.alive)
      .subscribe(() => {
        this.api.getClients().subscribe((clients: Client[]) => {
          this.clients = clients.sort((a: Client, b: Client) => {
            if (a.connected && !b.connected) {
              return -1;
            }
            if (!a.connected && b.connected) {
              return 1;
            }
            return 0;
          });
        });
        this.api.getStreams().subscribe((streams: Stream[]) => {
          this.streams = streams;
        });
        this.api.getMopidyServers()
          .first()
          .subscribe((mopidyServers: MopidyServer[]) => {
            this.mopidyServers = mopidyServers;
          });
      });
  }

  public getMopidyServerNameForClient(client: Client): string|null {
    const mopidyServer = this.mopidyServers.find((each: MopidyServer, index: number) => {
      return each.name.startsWith(client.id);
    });

    return mopidyServer !== undefined ? mopidyServer.name : null;
  }

  ngOnDestroy(): void {
    this.alive = false;
  }
}

<div class="row">
  <div class="col-12 col-sm-6 col-lg-4 col-xl-3" *ngFor="let client of clients">
    <div class="card mb-2">
      <div class="card-body">
        <h4 class="card-title">{{ client.id }}</h4>
        <h6 class="card-subtitle mb-2 text-muted" *ngIf="isAdmin">Latenz: {{ client.latency }}</h6>
      </div>
      <div class="list-group list-group-flush">
        <div class="list-group-item list-group-item-danger" *ngIf="!client.connected">
          Nicht verbunden
        </div>
        <div *ngIf="client.connected">
          <!--{% for stream in sorted(server.streams, key=lambda stream: (stream.status != 'playing', not stream.friendly_name.startswith(client.identifier), stream.friendly_name)) %} -->
          <ng-container *ngFor="let stream of streams">
            <a *ngIf="stream.status == 'playing' || client.stream == stream.id || stream.id.startsWith(client.id)"
               href="javascript:void(0)"
               (click)="api.setStream(client, stream)"
               class="list-group-item list-group-item-action"
               [ngClass]="{'active': client.stream == stream.id, 'list-group-item-info': stream.id.startsWith(client.id)}">
              <i class="icon-stream-idle"
              [ngClass]="{'icon-stream-idle': stream.status == 'idle', 'icon-stream-playing': stream.status == 'playing'}"></i>
              <strong *ngIf="stream.status == 'playing'">{{ stream.id }}</strong>
              <ng-container *ngIf="stream.status != 'playing'">{{ stream.id }}</ng-container>
              <br />
              <div class="clearfix mt-1" *ngIf="stream.status == 'playing'">
                <img [src]="'data:image/png;base64,' + stream.meta.COVER" class="cover ml-2 float-right" *ngIf="stream.meta.COVER && stream.meta.COVER.length">
                <em>{{ stream.meta.TITLE }} {{ stream.meta.ARTIST ? ' - ' + stream.meta.ARTIST : '' }}</em>
              </div>
            </a>
          </ng-container>
        </div>
      </div>
      <div class="list-group-item list-group-item-danger" *ngIf="client.connected && client.muted">
        Ton ist ausgeschaltet!
      </div>
      <div class="card-body" *ngIf="client.connected || isAdmin">
        <a href="javascript:void(0)" *ngIf="client.connected && client.muted" (click)="api.unmute(client)"
           class="card-link">Ton einschalten</a>
        <a href="javascript:void(0)" *ngIf="client.connected && !client.muted" (click)="api.mute(client)"
           class="card-link">Ton ausschalten</a>
        <a href="javascript:void(0)" *ngIf="isAdmin" (click)="api.delete(client)"
             class="card-link text-danger">Löschen</a>
      </div>
      <div class="card-body" *ngIf="client.connected && getMopidyServerNameForClient(client) !== null">
        <a [routerLink]="['/browse']" [queryParams]="{name: getMopidyServerNameForClient(client), play: false}" class="card-link">Lokale Musik ändern</a>
      </div>
      <div class="card-body" *ngIf="isAdmin">
        <div class="input-group">
          <input #latency type="number" min="0" name="latency" value="{{ client.latency }}" class="form-control"
                 placeholder="Latenz" aria-label="Latenz">
          <span class="input-group-btn">
              <button class="btn btn-secondary" type="submit"
                      (click)="api.setLatency(client, latency.value)">Speichern</button>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>

// frontend-react/src/components/streams/Streams.tsx
import React, { useEffect, useState } from "react";
import "./Streams.css";
import { Client, Stream, MopidyServer } from "../../entities";
import { Link } from "react-router-dom";
import clsx from "clsx";
import { useIsAdmin, times } from "../../util";
import { interval } from "rxjs";
import { exhaustMap, filter } from "rxjs/operators";
import { Api } from "../../api";
import ContentLoader from 'react-content-loader'

const ClientColumn = ({ client, streams, mopidyServers }: { client: Client, streams: Stream[], mopidyServers: MopidyServer[] }) => {
  const isAdmin = useIsAdmin();
  const [latency, setLatency] = useState(client.latency);

  function getMopidyServerNameForClient(client: Client): string | null {
    const mopidyServer = mopidyServers.find((each: MopidyServer) => each.name.startsWith(client.id));
    return mopidyServer !== undefined ? mopidyServer.name : null;
  }

  const mopidyServerName = getMopidyServerNameForClient(client);

  return <>
    <div className="card mb-2">
      <div className="card-body">
        <h4 className="card-title">{client.id}</h4>
        {isAdmin && <h6 className="card-subtitle mb-2 text-muted">Latenz: {client.latency}</h6>}
      </div>
      <div className="list-group list-group-flush">
        {!client.connected
          ? <div className="list-group-item list-group-item-danger">
            Nicht verbunden
        </div>
          : <div>
            {/*{% for stream in sorted(server.streams, key=lambda stream: (stream.status != 'playing', not stream.friendly_name.startswith(client.identifier), stream.friendly_name)) %} */}
            {streams.map(stream => <React.Fragment key={stream.id}>
              {(stream.status === 'playing' || client.stream === stream.id || stream.id.startsWith(client.id)) &&
                <button onClick={() => Api.setStream(client, stream)} className={clsx("list-group-item", "list-group-item-action", {
                  'active': client.stream === stream.id,
                  'list-group-item-info': stream.id.startsWith(client.id)
                })}>
                  <i className={clsx("icon-stream-idle", {
                    'icon-stream-idle': stream.status === 'idle',
                    'icon-stream-playing': stream.status === 'playing'
                  })} />
                  {stream.status === 'playing' ? <strong>{stream.id}</strong> : <>{stream.id}</>}
                  <br />
                  {stream.status === 'playing' &&
                    <div className="clearfix mt-1">
                      {stream.meta.COVER && stream.meta.COVER.length && <img src={'data:image/png;base64,' + stream.meta.COVER} className="cover ml-2 float-right" alt="" />}
                      <em>{stream.meta.TITLE} {stream.meta.ARTIST ? ' - ' + stream.meta.ARTIST : ''}</em>
                    </div>}
                </button>}
            </React.Fragment>)}
          </div>
        }
      </div>{client.connected && client.muted &&
        <div className="list-group-item list-group-item-danger">
          Ton ist ausgeschaltet!
  </div>}
      {(client.connected || isAdmin) &&
        <div className="card-body">
          {client.connected && client.muted && <button onClick={() => Api.unmute(client)} className="btn btn-link p-0 card-link">Ton einschalten</button>}
          {client.connected && !client.muted && <button onClick={() => Api.mute(client)} className="btn btn-link p-0 card-link">Ton ausschalten</button>}
          {isAdmin && <button onClick={() => Api.delete(client)} className="btn btn-link p-0 card-link text-danger">Löschen</button>}
        </div>}
      {client.connected && mopidyServerName !== null &&
        <div className="card-body">
          <Link to={`/browse?name=${encodeURIComponent(mopidyServerName)}&play=0`} className="card-link">Lokale Musik ändern</Link>
        </div>}
      {isAdmin &&
        <div className="card-body">
          <div className="input-group">
            <input type="number" min={0} name="latency" value={latency} onChange={(event) => setLatency(parseInt(event.target.value))} className="form-control" placeholder="Latenz" aria-label="Latenz" />
            <span className="input-group-append">
              <button className="btn btn-secondary" type="submit" onClick={() => Api.setLatency(client, latency)}>Speichern</button>
            </span>
          </div>
        </div>}
    </div></>
}

const StreamSkeleton = () => {
  const rows = 6;
  const rowHeight = 40;
  const rowWidth = 250;
  const rowPadding = 5;

  const height = (rows + 1) * (rowHeight + rowPadding);

  return <ContentLoader
    speed={2}
    width={"100%"}
    height={height}
    viewBox={`0 0 ${rowWidth} ${height}`}
    backgroundColor="#f3f3f3"
    foregroundColor="#ecebeb"
  >
    {times(rows, i =>
      <rect key={i} x={0} y={(i > 0 ? i + 1 : 0) * (rowHeight + rowPadding)} rx="5" ry="5" width={rowWidth} height={i === 0 ? rowHeight * 2 : rowHeight} />
    )}
  </ContentLoader>;
}

const Streams = () => {
  const [streams, setStreams] = useState<Stream[]>([]);
  const [clients, setClients] = useState<Client[]>([]);
  const [mopidyServers, setMopidyServers] = useState<MopidyServer[]>([]);
  const [state, setLoadingState] = useState<"loading" | "done">("loading");

  useEffect(() => {
    const subscription = interval(2000)
      .pipe(
        // Do not constantly update if the window is hidden
        filter(() => !document.hidden),
        exhaustMap(async () => {
          try {
            const clients = await Api.getClients();
            const streams = await Api.getStreams();
            const mopidyServers = await Api.getMopidyServers();

            setClients(clients.sort((a: Client, b: Client) => {
              if (a.connected && !b.connected) {
                return -1;
              }
              if (!a.connected && b.connected) {
                return 1;
              }
              return 0;
            }));
            setStreams(streams);
            setMopidyServers(mopidyServers);
            setLoadingState("done");
          } catch (e) {
            setLoadingState("loading");
          }
        })
      )
      .subscribe();
    return () => subscription.unsubscribe();
  }, []);

  return <div className="row">
    {state === "loading"
      ? times(4, i =>
        <div className="col-12 col-sm-6 col-lg-4 col-xl-3" key={i}>
          <StreamSkeleton />
        </div>)
      : clients.map(client =>
        <div className="col-12 col-sm-6 col-lg-4 col-xl-3" key={client.id}>
          <ClientColumn client={client} streams={streams} mopidyServers={mopidyServers} />
        </div>
      )}

  </div>
}

export default Streams;
